-- storage provider
CREATE TABLE storage_provider (
    id BIGINT PRIMARY KEY,
    sp_id INT NOT NULL,
    operator_address TEXT NOT NULL,
    funding_address TEXT NOT NULL,
    seal_address TEXT NOT NULL,
    approval_address TEXT NOT NULL,
    gc_address TEXT NOT NULL,
    total_deposit NUMERIC,
    status TEXT,
    endpoint TEXT,
    moniker TEXT,
    identity TEXT,
    website TEXT,
    security_contact TEXT,
    details TEXT,
    bls_key TEXT,
    update_time_sec BIGINT,
    read_price NUMERIC,
    free_read_quota BIGINT,
    store_price NUMERIC,
    create_at BIGINT,
    create_tx_hash TEXT NOT NULL,
    update_at BIGINT,
    update_tx_hash TEXT NOT NULL,
    removed BOOLEAN DEFAULT FALSE,
    UNIQUE (sp_id)
);
CREATE INDEX idx_sp_id ON storage_provider (sp_id);
-- global_virtual_group_family
CREATE TABLE global_virtual_group_family (
    id INT PRIMARY KEY,
    global_virtual_group_family_id INT NOT NULL,
    primary_sp_id INT NOT NULL,
    global_virtual_group_ids TEXT,
    virtual_payment_address TEXT NOT NULL,
    create_at BIGINT,
    create_tx_hash TEXT NOT NULL,
    create_time TIMESTAMPTZ,
    update_at BIGINT,
    update_tx_hash TEXT NOT NULL,
    update_time TIMESTAMPTZ,
    removed BOOLEAN DEFAULT FALSE,
    UNIQUE (global_virtual_group_family_id),
    UNIQUE (primary_sp_id),
    CONSTRAINT fk_spid FOREIGN KEY (primary_sp_id) REFERENCES storage_provider(sp_id)
);
-- global_virtual_group
CREATE TABLE global_virtual_group (
    id BIGINT PRIMARY KEY,
    global_virtual_group_id INT NOT NULL,
    family_id INT NOT NULL,
    primary_sp_id INT NOT NULL,
    secondary_sp_ids TEXT,
    stored_size BIGINT NOT NULL,
    virtual_payment_address TEXT,
    total_deposit NUMERIC,
    create_at BIGINT NOT NULL,
    create_tx_hash TEXT NOT NULL,
    create_time TIMESTAMPTZ NOT NULL,
    update_at BIGINT NOT NULL,
    update_tx_hash TEXT NOT NULL,
    update_time TIMESTAMPTZ NOT NULL,
    removed BOOLEAN DEFAULT FALSE,
    UNIQUE (global_virtual_group_id),
    CONSTRAINT fk_primary_spid FOREIGN KEY (primary_sp_id) REFERENCES storage_provider(sp_id),
    CONSTRAINT fk_family_id FOREIGN KEY (family_id) REFERENCES global_virtual_group_family(global_virtual_group_family_id)
);
CREATE TABLE local_virtual_group (
    id BIGINT PRIMARY KEY,
    local_virtual_group_id INT NOT NULL,
    global_virtual_group_id INT NOT NULL,
    bucket_id INT NOT NULL,
    stored_size BIGINT,
    create_at BIGINT,
    create_tx_hash TEXT NOT NULL,
    create_time TIMESTAMPTZ,
    update_at BIGINT,
    update_tx_hash TEXT NOT NULL,
    update_time TIMESTAMPTZ,
    removed BOOLEAN DEFAULT FALSE,
    UNIQUE (local_virtual_group_id),
    UNIQUE (global_virtual_group_id),
    UNIQUE (bucket_id),
    UNIQUE (local_virtual_group_id, bucket_id)
);