INSERT INTO object (
        id,
        bucket_id,
        bucket_name,
        object_id,
        object_name,
        creator_address,
        owner_address,
        local_virtual_group_id,
        operator_address,
        payload_size,
        visibility,
        content_type,
        status,
        redundancy_type,
        source_type,
        checksums,
        delete_at,
        delete_reason,
        create_at,
        create_tx_hash,
        create_time,
        update_at,
        update_tx_hash,
        sealed_tx_hash,
        update_time,
        removed,
        tags,
        is_updating,
        content_updated_time,
        updater,
        version
    )
VALUES (
        1,
        1,
        'bucket1',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef01',
        'object1.txt',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        1,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        1024,
        'public',
        'text/plain',
        'active',
        'typeA',
        'sourceA',
        '{"checksum1", "checksum2"}',
        NULL,
        NULL,
        1620000010,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-18 12:00:00+00',
        1620000010,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-18 13:00:00+00',
        FALSE,
        '{"key": "value"}',
        FALSE,
        '2023-08-18 13:00:00+00',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        1
    ),
    (
        2,
        2,
        'bucket2',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef02',
        'image2.jpg',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        2,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        2048,
        'private',
        'image/jpeg',
        'inactive',
        'typeB',
        'sourceB',
        '{"checksum1", "checksum2"}',
        NULL,
        NULL,
        1620000020,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-18 14:00:00+00',
        1620000020,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-18 15:00:00+00',
        FALSE,
        '{"key": "value"}',
        FALSE,
        '2023-08-18 15:00:00+00',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        1
    ),
    (
        3,
        3,
        'bucket3',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef03',
        'data3.json',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        3,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        3072,
        'public',
        'application/json',
        'active',
        'typeC',
        'sourceC',
        '{"checksum1", "checksum2"}',
        NULL,
        NULL,
        1620000030,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-18 16:00:00+00',
        1620000030,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-18 17:00:00+00',
        FALSE,
        '{"key": "value"}',
        FALSE,
        '2023-08-18 17:00:00+00',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        1
    ),
    (
        4,
        4,
        'bucket4',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef04',
        'object4.html',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        4,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        4096,
        'private',
        'text/html',
        'inactive',
        'typeD',
        'sourceD',
        '{"checksum1", "checksum2"}',
        NULL,
        NULL,
        1620000040,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-18 18:00:00+00',
        1620000040,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-18 19:00:00+00',
        FALSE,
        '{"key": "value"}',
        FALSE,
        '2023-08-18 19:00:00+00',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        1
    ),
    (
        5,
        5,
        'bucket5',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef05',
        'report5.pdf',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        5,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        5120,
        'public',
        'application/pdf',
        'active',
        'typeE',
        'sourceE',
        '{"checksum1", "checksum2"}',
        NULL,
        NULL,
        1620000050,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-18 20:00:00+00',
        1620000050,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-18 21:00:00+00',
        FALSE,
        '{"key": "value"}',
        FALSE,
        '2023-08-18 21:00:00+00',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        1
    ),
    (
        6,
        6,
        'bucket6',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef06',
        'video6.mp4',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        6,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        6144,
        'private',
        'video/mp4',
        'inactive',
        'typeF',
        'sourceF',
        '{"checksum1", "checksum2"}',
        NULL,
        NULL,
        1620000060,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-18 22:00:00+00',
        1620000060,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-18 23:00:00+00',
        FALSE,
        '{"key": "value"}',
        FALSE,
        '2023-08-18 23:00:00+00',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        1
    ),
    (
        7,
        7,
        'bucket7',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef07',
        'audio7.mp3',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        7,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        7168,
        'public',
        'audio/mpeg',
        'active',
        'typeG',
        'sourceG',
        '{"checksum1", "checksum2"}',
        NULL,
        NULL,
        1620000070,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-19 00:00:00+00',
        1620000070,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-19 01:00:00+00',
        FALSE,
        '{"key": "value"}',
        FALSE,
        '2023-08-19 01:00:00+00',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        1
    ),
    (
        8,
        8,
        'bucket8',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef08',
        'archive8.zip',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        8,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        8192,
        'private',
        'application/zip',
        'inactive',
        'typeH',
        'sourceH',
        '{"checksum1", "checksum2"}',
        NULL,
        NULL,
        1620000080,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-19 02:00:00+00',
        1620000080,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-19 03:00:00+00',
        FALSE,
        '{"key": "value"}',
        FALSE,
        '2023-08-19 03:00:00+00',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        1
    ),
    (
        9,
        9,
        'bucket9',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef09',
        'data9.bin',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        9,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        9216,
        'public',
        'application/octet-stream',
        'active',
        'typeI',
        'sourceI',
        '{"checksum1", "checksum2"}',
        NULL,
        NULL,
        1620000090,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-19 04:00:00+00',
        1620000090,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-19 05:00:00+00',
        FALSE,
        '{"key": "value"}',
        FALSE,
        '2023-08-19 05:00:00+00',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        1
    ),
    (
        10,
        10,
        'bucket10',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef10',
        'dataset10.csv',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        10,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        10240,
        'private',
        'text/csv',
        'inactive',
        'typeJ',
        'sourceJ',
        '{"checksum1", "checksum2"}',
        NULL,
        NULL,
        1620000100,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-19 06:00:00+00',
        1620000100,
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        '2023-08-19 07:00:00+00',
        FALSE,
        '{"key": "value"}',
        FALSE,
        '2023-08-19 07:00:00+00',
        '0xabcdefabcdefabcdefabcdefabcdefabcdefabcdef',
        1
    );